export const roles = {
  'Sales Assistant': ['make_sales'],
  'Manager': [
    'make_sales',
    'add_product',
    'view_products',
    'add_employee',
    'view_employees',
    'view_reports',
  ],
  'Admin': [
    'make_sales',
    'add_product',
    'view_products',
    'edit_products',
    'delete_products',
    'add_employee',
    'view_employees',
    'edit_employees',
    'delete_employees',
    'view_reports',
  ],
  'Owner': [
    'make_sales',
    'add_product',
    'view_products',
    'edit_products',
    'delete_products',
    'add_employee',
    'view_employees',
    'edit_employees',
    'delete_employees',
    'view_reports',
  ],
};
